worker_processes  2;
error_log  /var/log/nginx/error.log notice;
pid        /var/run/nginx.pid;
events {
    worker_connections  10240;
}

stream {

    map_hash_bucket_size 128;

    map $ssl_preread_server_name $name {
        service.cn-beijing-vpc.maxcompute.aliyun-inc.com            maxcompute;
        default                  deny_access;
    }

    upstream maxcompute{
        server service.cn-beijing-vpc.maxcompute.aliyun-inc.com:443;
    }


    upstream deny_access {
        server 0.0.0.1:1;
    }

    server {
        listen      8443;
        proxy_pass  $name;
        ssl_preread on;
    }

}
